# Generated by Django 4.1.7 on 2023-04-07 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_order_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='author',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('NO', 'Novel'), ('JO', 'Journal'), ('MA', 'Magazine'), ('AR', 'Article'), ('LE', 'Legal Case'), ('BL', 'Blog'), ('TH', 'Thesis')], max_length=200, null=True),
        ),
    ]
