# Generated by Django 4.1.7 on 2023-04-07 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_remove_order_tags_product_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='data_created',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='email',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='phone',
        ),
    ]
