# Generated by Django 4.1.7 on 2023-04-07 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_remove_tag_data_created_remove_tag_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='source',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
