# Generated by Django 4.1.7 on 2023-04-07 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_product_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='source',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
