# Generated by Django 4.1.7 on 2023-04-07 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_product_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.DateTimeField(auto_now_add=True, choices=[('Pending', 'Pending'), ('Out for delivery', 'Out for delivery'), ('Delivered', 'Delivered')], null=True),
        ),
    ]
