# Generated by Django 4.1.7 on 2023-04-09 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Reserved', 'Reserved'), ('Available', 'Available')], max_length=200, null=True),
        ),
    ]
