# Generated by Django 4.1.7 on 2023-04-14 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('Novel', 'Novel'), ('Journal', 'Journal'), ('Magazine', 'Magazine'), ('Article', 'Article'), ('Legal Case', 'Legal Case'), ('Blog', 'Blog'), ('Thesis', 'Thesis')], max_length=200, null=True),
        ),
    ]
